# Generated by Django 4.0.4 on 2023-03-11 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number format is not valid.', regex='^(0|\\+98|0098)9[0-9]{9}$')]),
        ),
    ]
