# Generated by Django 4.0.4 on 2023-03-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
