# Generated by Django 3.2.6 on 2023-03-07 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import json 


def create_categories(apps, _):
    Category = apps.get_model("blog", "Category")
    Article = apps.get_model("blog", "Article")
    User = apps.get_model("account", "User")
    
    with open(settings.BASE_DIR / 'blog/fixtures/articles.json', 'r') as f:
        articles = json.load(f)
        
    for article in articles:
        Article.objects.filter(pk=article["pk"]).update(
            category=Category.objects.get_or_create(title=article["fields"]["category"])[0],
            author=User.objects.get_or_create(username=article["fields"]["author"])[0],
            published=models.F("created"),
            updated=models.F("created"),
            status="p"
        )



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'publish')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.RunPython(
            code=create_categories,
            reverse_code=migrations.RunPython.noop
        )
    ]
